REQUIRE, src/providers/ijulia_setup.jl
https://github.com/JuliaIO/JSON.jl/commit/495c75ff122abcac409cc79b7c4bc7d005872d7a
=> JSON 0.7 min ver for JSON.lower

assets/basics/node.js, assets/basics/webio.js, src/WebIO.jl, src/node.jl, src/providers/atom_setup.jl, src/providers/blink_setup.jl, src/providers/ijulia_setup.jl, src/providers/mux_setup.jl, src/widget.jl
See the commit messages for details
Todo
=> Widget lifecycle notifications, register_renderable, nested scripts, and attrUtils

assets/basics/node.js
#23 merged into this branch not master (which makes sense - I was seeing what happened when you PR not against master over there)
=> Merge requires stuff into master

src/util.jl, test/runtests.jl, test/util-tests.jl
Maybe these exist somewhere else? Was easier to implement them than to find them... :/
=> Adds kebab2camel and camel2kebab

assets/basics/webio.js, assets/webpack.config.js, src/node.jl, src/syntax.jl, src/widget.jl
Requires https://github.com/JuliaGizmos/Observables.jl/pull/8
Also fixes #12
=> Enables Observables to share and update across widgets

assets/webio/dist/bundle.js, assets/webio/node.js, assets/webio/package.json, assets/webio/unsafe_script.js, assets/webio/webio.js, deps/_bundlejs.jl, src/node.jl, src/render.jl, src/scope.jl, test/blink-tests.jl
They should ideally all be in sync, but at  least not remove each other when displayed :laughing: 
Ended up removing a handful of warts
=> WIP: address issues when the same scope is displayed many times

src/imports.jl
=> Refactor import to get google fonts working (/css)

deps/jlstaticserve.py
=> make `JuliaPackageAssetServer.get()` a coroutine

assets/webio/package.json
related to: https://github.com/JuliaGizmos/WebIO.jl/issues/72
=> Reduce webpack restriction

deps/build.jl
=> use homedir instead of accessing ENV directly

test/runtests.jl
(just some low-hanging fruit for improving test coverage)
=> Test text/plain rendering of nodes

assets/webio/dist/bundle.js, assets/webio/unsafe_script.js, assets/webio/webio.js, src/WebIO.jl, src/iframe.jl
Can be used to fight pre-existing stylesheets and event handlers.
cc @rdeits 
I'm now trying to get the height to be the same as content (doesn't work when content < 150px). ~Another issue is observables don't sync between the parent and the frame (e.g. slider)~
=> WIP: IFrame wrapper

README.md
This addresses issue https://github.com/JuliaGizmos/WebIO.jl/issues/41
-----
It doesn't have to be displayed so prominently. I just thought it might encourage people to submit their projects.
=> Add demo section to readme

src/util.jl
=> use UUID4s for scope IDs instead of an increasing integer

deps/build.jl
=> fix duplicate webio jupyter notebook config entries

src/iframe.jl, src/providers/ijulia.jl
Fixes #120 
Obviously, the solution to our regex problem is more regex :upside_down_face:
=> make href regexes non-greedy

examples/jupyter-demo.ipynb, test/REQUIRE, test/ijulia-tests.jl
This basically just automates the process I've been doing by hand every time I touch something ijulia-specific.
=> Add example jupyter notebook and test that it runs

src/WebIO.jl
=> suppress debug statements for normal usage

REQUIRE, src/WebIO.jl, src/node.jl, src/providers/blink.jl, src/providers/ijulia.jl, src/providers/mux.jl, src/render.jl, src/scope.jl, src/syntax.jl
This doesn't quite get WebIO working on 0.7 due to some issues with Requires, but it's an improvement.
=> fix some deprecations for 0.7

examples/p5.jl
The real fix is https://github.com/JunoLab/Blink.jl/pull/89 but at least this makes the example work properly.
=> fix p5.jl example with Blink

src/imports.jl, src/providers/ijulia.jl, src/providers/mux.jl
=> Register bundle.js and helpers via AssetRegistry in IJulia and Mux

src/imports.jl
There was a problem here when checking for the a full path that's already registered.
cc @ranjanan
=> bug fix asset registration

src/render.jl
This fixes #150 (code snippet from `@shashi`).  Seems to work so far but maybe better to test a bit more before merging.
=> fix #150 : render content of observables

src/WebIO.jl, src/imports.jl, src/providers/ijulia.jl, src/providers/mux.jl
=> Allow configuration of base URL

deps/build.jl
fix one part of the issue in #160
=> propperly escape paths on windows

src/node.jl, test/REQUIRE, test/ijulia-tests.jl
=> A few minor improvements

README.md, examples/jupyter-demo.ipynb, src/providers/ijulia.jl
Somehow this was overlooked when porting things to the new Requires package.
=> fix undefined error in ijulia provider

assets/webio/jupyterlab_entry.js
#196 didn't account for this.
It works even after a reload in JupyterLab :-o
=> Fix Jupyterlab communication

README.md, REQUIRE, assets/providers/websocket_connection.js, src/WebIO.jl, src/providers/generic_http.jl, test/REQUIRE, test/http-tests.jl, test/runtests.jl
just the non forked version of #198
=>  implement generic http provider

src/imports.jl
=> fix imports 

src/providers/generic_http.jl
=> remove potentially wrong content-type

src/providers/generic_http.jl, test/http-tests.jl
=> remove wrong normpath, allow to customize bundle url

src/syntax.jl, test/syntax.jl
Fixes #111.
Requesting review from @shashi and @piever because writing idiomatic Julia isn't exactly my strong suit.
=> Fix @js_str interpolation issues.

src/scope.jl
Ping @shashi (please merge if this looks okay).
This needs to be updated in MeshCat.jl as well because their implentation is broken.
=> Add wait method for Scope and ConnectionPool.

src/iframe.jl
Fixes (part of) #261.
Not all of the MeshCat tests pass yet.
=> Wrap iframes in a scope.

deps/build.jl
thanks to @hhaensel (ref https://github.com/JuliaGizmos/WebIO.jl/issues/236#issuecomment-484428662)
=> %APPDATA% is not inside home directory

src/scope.jl
=> Change scope documentation.

src/WebIO.jl, src/asset.jl, src/connection.jl, src/messaging.jl, src/node.jl, src/scope.jl, src/syntax.jl, src/util.jl
Closes #289.
There are some other things that we could tackle either in this PR or other ones. The initial commit only moves code around and doesn't add or remove anything.
Pinging basically everyone: @shashi @SimonDanisch @rdeits @piever @pfitzseb.
=> Refactor file structure.

src/connection.jl
The lack of this made tracking down https://github.com/JunoLab/Blink.jl/pull/206 a NIGHTMARE.
=> Cleanup connection.jl (don't swallow errors).

deps/jupyter.jl, packages/jupyter-lab-provider/src/labextension.ts, packages/package.json
=> Fix JupyterLab plugin (no more WebIO not detected).

deps/jupyter.jl
Issue #349: This change updates the function name from install_webio_nbextension to install_jupyter_nbextension
=> Update function name in docstring

docs/src/troubleshooting/not-detected.md
trouble shooting help for Jupyter Hub
=> Update not-detected.md to include Jupyter Hub troubleshooting info

.github/workflows/tests.yml
Finally getting around to moving away from Travis CI (RIP)
=> Add GH action to run tests
