assets/basics/webio.js

Adds a function that takes an string of html to replace the contents of an element,
and ensures any scripts in the html string get run. This can be done using `element.innerHTML = htmlstr` but any scripts won't get run.
Used in InteractNext to auto-update display of Observables here: https://github.com/JuliaGizmos/InteractNext/blob/master/src/observablesIO.jl#L32

RFC: Adds function to replace html contents and run scripts

---

src/WebIO.jl
src/providers/atom_setup.jl

WebIO.setup() no longer explicitly required to be called by the user.
N.b. this is a PR against my other PR 😄 - just wanted to see if I can change the branch I'm comparing against after you merge the other one.

Runs WebIO.setup() using Requires.jl

---

assets/basics/node.js
src/syntax.jl

Just the final commit is relevant, the others are in #25 which should be merged first
This section of the code avoids loading css files twice if they have already been loaded.
`location.pathname` is the current browser url, `imp.url` is the url of the css file
Before this you couldn't load more than one css file - as `location.pathname` stays the same on both imports. This fixes it.

Css load fix

---

assets/basics/node.js
src/node.jl
src/syntax.jl

(This PR is only for the last commit, merge #25 then #26 first)
Previously, interpolated functions were generally in double quotes so they weren't `eval`ed correctly. This meant you couldn't define say Dicts with callback functions as values to include into later code.
Example:
```
using WebIO
jsobj = Dict(:hi=>@js function() hi end)
jscode = @js function()
$jsobj
end
jscode.s |> println
```
Before: `(function (){return {"hi":"(function (){ alert("hi") })"}})`
After:    `(function (){return {"hi":(function (){ alert("hi") })}})`
Note the double quotes around the nested "hi" function.
edit: Also has a small fix for named functions without arguments

Fix JSONification of interpolated `@js` function code 

---

assets/basics/node.js
src/node.jl
src/syntax.jl
src/widget.jl

Enables registering a callback in `show(n::Node, ...)`, which is a way for a single Widget to be displayed multiple times (there will be multiple js contexts associated with the same Julia Widget).
Also
* `after` now called with `apply` not `call`, meaning, for example, each dependency for ondependencies, is now passed as a separate argument, rather than the first argument holding an array.
* command and event handlers updated for new JSEvalSerializer JSON regime
* offjs method added (untested/unused in the end)
* Syntax for `+=` added for js macros

Multi widget display and event and command handlers updated

---

assets/basics/webio.js
src/WebIO.jl
src/node.jl

Also, adds recording of which backend providers have been initialised

Stops `show`'s rampant piracy and fixes error in unencode_scripts

---

assets/basics/node.js
assets/basics/webio.js
assets/package.json
src/WebIO.jl
src/render.jl

Adds default rendering for all types using richest show. This won't generally be used unless register_renderable(::Type) is called but can come in handy. E.g. InteractNext uses it to display auto-updating Observables
Fixes array valued observable updating. Turns out that in js `["a"] !== ["a"]` - this deals with that in the context of propagating observable updates

Default rendering for all types and Observable Array Fixes

---

REQUIRE
assets/basics/webio.js
src/render.jl
src/syntax.jl
test/blink-tests.jl
test/syntax.jl

* removes console.log on every message
* fixes parsing when props have `.`s in them, e.g. dom"img[src=image.jpg]. fixes #34
* adds test for the above
* improves dom_str hygiene (was overwriting tagstr, tag, props in user context)
* fixes Blink test with Observables updates
edit:
* and span changed to pre for Text

Remove JS Message Logging and Fix issue with dots in dom_str props

---

README.md
assets/webio/node.js
assets/webio/webio.js
awkward.md
examples/blink_counter.jl
examples/mux_counter.jl
examples/p5.jl
src/WebIO.jl
src/connection.jl
src/imports.jl
src/providers/atom_setup.jl
src/providers/blink_setup.jl
src/providers/ijulia_setup.jl
src/providers/mux_setup.jl
src/scope.jl
src/syntax.jl
test/blink-tests.jl
test/communication.jl

The name "Widget" had little to do with what it did. "Context" is too ambiguous. "Scope" says some things are defined within this scope. We define dependencies and observables.

Rename Widget to Scope

---

src/WebIO.jl
src/connection.jl
src/providers/blink_setup.jl
src/providers/ijulia_setup.jl
src/providers/mux_setup.jl
src/scope.jl
test/communication.jl

This is a rough proposal to fix #71. It replaces the `Scope`'s `outbox` field with a new struct, `ConnectionPool` that holds both the outbox of messages and a set of connections to send those messages to. On construction, the connection pool starts a task that will block until a connection is made, and then will send each message the outbox receives to every open connection. 
Anyway, please let me know if this seems like the right solution.

Enable messages to be sent to many web connections

---

src/scope.jl
test/communication.jl

Previously, if you did the following:
1. add connection A
2. add connection B
3. send message 1
4. send message 2
then connection A would receive messages 1 and 2, but connection B would only receive 2. That's because the `process_messages()` task would advance past `ensure_connection` when the first connection was found, which meant that connection 2 would not be found until the second message. 
Flipping the order in which we wait for connections and messages fixes the issue, and I've added some tests to make sure.

fix order of operations in process_messages

---

assets/webio/dist/bundle.js
assets/webio/unsafe_script.js
src/providers/ijulia_setup.jl

attempts to resolve: 
+ https://github.com/JuliaGizmos/WebIO.jl/issues/72

Get WebIO working on Binder

---

src/WebIO.jl
src/providers/atom.jl
src/providers/blink.jl
src/providers/ijulia.jl
src/providers/mux.jl

Fixes #104 
Fixes #105 (using the same change mentioned in that issue)
I find this a bit easier to understand than the current version in `master`, but ultimately whether this is better than the `eval(Main, include(...))` approach is a matter of opinion. What do you think?

Use `@require` directly to set up providers, instead of `eval(Main, include(...))` 

---

assets/webio/test/trivial_import.js
test/blink-tests.jl

This PR adds tests for scope imports with the following URL types:
* `/pkg/Foo/...`
* `pkg/Foo/...`
* `//public/url/...`
* `http://public/url/...`
~~Currently only the first one actually works on Blink (see #107 ), so we should fix those issues before merging.~~
Edit: all 4 URLs are working now! 
In the long run, we can change the public URL used here to the permanent github URL of the `trivial_import.js` file, but since it's not committed yet I'm currently just serving it from my personal public folder. That's easy to change later.

Add a test for scope imports in Blink

---

src/scope.jl

Currently, a scope which is not yet being rendered anywhere can only accept 32 messages before it starts blocking. I don't think there's any reason for that limit to exist, so I've removed it.

don't limit the number of pending messages for a scope

---

src/providers/atom.jl
src/providers/blink.jl
src/providers/ijulia.jl
src/providers/mux.jl
src/render.jl
test/blink-tests.jl

resolves #119
Now, each provider defines `register_renderable(::Type{T}, ::Val{provider})` so their method signatures don't conflict and there should be no dependence on load order.

refactor register_renderable to not rely on overwriting a method

---

README.md

because that's the actual javascript function :wink:

Math.rand() -> Math.random() in the Readme

---

assets/webio/dist/bundle.js
assets/webio/webio.js
src/scope.jl

This is necessary to get Knockout to work properly if I understand correctly. cc @piever 
This makes https://github.com/JuliaGizmos/Vue.jl/pull/10 necessary. We should release them both in tandem.
closes #39 against @JobJob's will?? :-P Let me know if you still think we really need this check here! My reasoning is [here](https://github.com/JuliaGizmos/Vue.jl/pull/10#issuecomment-399850249)

Don't prevent an update if the value doesn't change

---

assets/providers/mux_setup.js
assets/webio/dist/bundle.js
assets/webio/webio.js

After doing this change I realized that we assume Mux to be running on the root of the domain when we assume `/assetserver/hash` urls will work. But this is quite robust anyway.

Make Mux work on non-root routes

---

README.md
REQUIRE
examples/jupyter-demo.ipynb
src/WebIO.jl
src/iframe.jl
src/node.jl
src/scope.jl
src/syntax.jl
test/blink-tests.jl
test/ijulia-tests.jl
test/node.jl
test/runtests.jl

This implements the suggestion I made in #156 (and fixes #156 ). 
It's kind of obnoxious to ask users to switch from `Node()` to `node()` in their code, so I'm open to other suggestions. 
For example, instead of doing this, we could keep the vararg `Node()` constructor as-is and replace all our internal usage with a new `_node_internal()` constructor that takes an `AbstractVector` of children. 
But in either case, I think we should be sure that the user-facing constructor has *only* the vararg method, rather than having the ambiguous vararg and Vector methods.

Proposal: new `node()` vararg constructor

---

.gitignore
deps/build.jl
src/imports.jl
src/node.jl
src/render.jl

These weren't covered by WebIO tests but result in errors on 1.0 with RigidBodySim.

[PR against rd/v0.7-redux] More fixes for 1.0

---

.gitignore
.travis.yml
README.md
REQUIRE
assets/providers/mux_setup.js
deps/_bundlejs.jl
deps/build.jl
deps/jlstaticserve.py
examples/counter.jl
examples/jupyter-demo.ipynb
examples/p5.jl
src/WebIO.jl
src/connection.jl
src/imports.jl
src/node.jl
src/providers/atom.jl
src/providers/blink.jl
src/providers/ijulia.jl
src/providers/mux.jl
src/render.jl
src/scope.jl
src/syntax.jl
src/util.jl
test/REQUIRE
test/blink-tests.jl
test/bundling.jl
test/communication.jl
test/mux-tests.jl
test/runtests.jl
test/util-tests.jl

Combines #145 and #157 
Fixes #172 
Fixes #164 
Fixes #128 
Fixes #47

another try at Julia v0.7 support

---

REQUIRE
src/WebIO.jl
src/node.jl
src/providers/atom.jl
src/providers/blink.jl
src/providers/mux.jl
src/render.jl

I'm moving methods from AbstractWidget here from InteractBase, so that it's easier to keep things in sync when the integration with other packages changes.

move widget methods from InteractBase

---

README.md
examples/jupyter-demo.ipynb
src/providers/ijulia.jl

@piever this is a PR into your branch from #180 . There was just another missing IJulia prefix (my fault) and the error message was lost since it was happening on some other task. With this, the basic ticking clock demo works for me in julia 0.7.

fix another missing IJulia prefix

---

REQUIRE
src/scope.jl

A cleaner way to do #178 : only use the `AbstractObservable` interface in WebIO, so it'll automatically work with all `AbstractObservables`

support abstractobservables

---

src/providers/mux.jl

This is a companion PR to https://github.com/JuliaWeb/Mux.jl/pull/70 to allow the user passing a host different than `localhost`. 
~I'm actually curious (both here and in https://github.com/JuliaWeb/Mux.jl/pull/70 ) whether we want positional of keyword arguments for this. One advantage of keyword is that we could allow to pass several `app` at the same time to `webio_serve` which is pretty useful for multi page applications.~
Actually there's never any need to splat as for serving many pages one can use the Mux infrastructure:
`webio_serve(Mux.stack(pages...), host, port)`
so we should not do keyword argument and stay consistent with Mux and HTTP I think.

allow custom host

---

src/util.jl
test/util-tests.jl

this ensures that seeding the global RNG cannot result in scopes with
duplicate IDs

use a private RNG to generate scope IDs

---

src/node.jl
test/node.jl

Completes the work started in #159 . We'll need to tag a new minor version after merging this.

remove deprecated `Node` vararg constructor

---

assets/webio/dist/bundle.js
assets/webio/node.js

If a Scope has messages in the outbox before being displayed, it would start to accept them before `onimport` callback is run.
This was not working well with Plots's approach of starting with an empty plot and then building the pieces in.
@sglyon let me know if this helps.

Delay _setup_scope until after onimport

---

src/imports.jl

Fix the `Base.warn_once`

---

REQUIRE
src/node.jl
src/providers/blink.jl
src/providers/mux.jl
src/render.jl

The idea with the current Widgets design is that all "graphical things" just forward stuff to `Widgets.render(x)` (separate from `WebIO.render`), so that packages different than WebIO can use `Widgets` (the plan is to add a Makie backend: https://github.com/JuliaPlots/AbstractPlotting.jl/pull/88). So basically for a Makie `Widget`, `Widgets.render(wdg)` would return a Makie object that would then be displayed with the Makie pipeline. The Mux and Blink methods should live in Mux and Blink to avoid type piracy but I thought we can move them when we move the rest.

reduce piracy to Widgets

---

src/rpc.jl
test/REQUIRE
test/blink-tests.jl
test/rpc.jl
test/test-utils.jl

Simplifies RPC API. You can now interpolate any Julia function.
```julia
js"""
async function() {
// Note: without `await`, this executes asynchronously.
// The println **should** start execution before the abs, but the order of completion
// is absolutely not guaranteed (except in IJulia, due to the fact that comms are
// synchronous).
$println("Print to Julia's stdout.");
console.log(await $abs(-3));
}
"""
```
Equivalently, using `Promise.then` rathern than `async` functions, you can write this.
```julia
js"""
function() {
$abs(-3).then((result) => console.log(result));
}
```
Requesting review from @shashi.

Simplify RPC API.

---

src/providers/generic_http.jl

The logger keyword is deprecated and it seems like one needs to use `WebIO.WEBIO_APPLICATION_MIME()` to get the correct `show` method.

update generic_http docstrings

---

src/imports.jl

This fixes errors in some cases where `//` ends up in the URL.

remove leading / from AssetRegsitry key

---

deps/build.jl
deps/jupyterdirs.jl

Fix %APPDATA% directory on Windows (for real this time).

---

deps/jupyter.jl

Thanks to @alecloudenback (comment on #294). Hopefully this fixes your issue.
This should also speed up the install time because previously the JupyterLab bundle was rebuild twice (once after the `labextension link` and once after the `labextension install` steps).

Defer building JupyterLab bundle

---

packages/package-lock.json
src/messaging.jl
src/render.jl
src/scope.jl
src/util.jl
test/runtests.jl
test/util-tests.jl

The scope ID should 100% internal, and no one should be able to mutate it... Or use it to name the scope. 
This change should be making sure of this. 
If packages actually used the ID to name the scopes, we should give an alternate option to name scopes, and not mix it with the ID.

Deprecate custom scope ids

---

src/scope.jl
test/deprecations.jl

Fixes https://github.com/JuliaGizmos/Interact.jl/issues/315.
The problematic bit of code seems to be [this line in Knockout.jl](https://github.com/JuliaGizmos/Knockout.jl/blob/1dd70973445e3ca1bfb8c98e3111ef18979e599b/src/Knockout.jl#L28-L30).

Fix bad deprecation for Scope constructor.

---

src/connection.jl
src/scope.jl
test/observable-node.jl

Ping @shashi.
tl;dr: when connections were being closed, we would buffer messages in the outbox forever. This is a problem when the outbox contains something like a reasonably sized image. Now, we drop messages if there are no connections (this is probably fine, especially once we implement allowing the frontend to pull the latest values of the observables) and is necessary to fix this issue. It should also be addressed in part by implementing scope reasoning.
Bug report source: https://github.com/JuliaGizmos/Interact.jl/issues/299

Fix memory leak in ConnectionPool when connections are closed.

---

src/connection.jl
test/bundling.jl
test/multiple-connections.jl

This also reworks the way that new channels are added to a scope to work more
synchronously and avoid some race conditions.
Fixes #337 .

Fix sending commands to multiple frontends.

---

.travis.yml
Project.toml
docs/make.jl
docs/src/messaging.md
src/WebIO.jl
src/connectionpool.jl
src/evaljs.jl
src/messaging.jl
src/rpc.jl
src/scope.jl
test/evaljs.jl
test/rpc.jl
test/runtests.jl
test/test-utils.jl

The goal of this PR is to rework WebIO's messaging system to be a little bit more simple and more extensible.
What this PR does/will do:
If we reduce the guarantees for sending commands, we need some other ways to do guaranteed delivery. One option is request/response (which we currently do, but is not well defined wrt multiple connections).
One option (that would be pretty close to how we do today) would be something like this.
```julia
s = Scope(dom=...)
display(s)
@async begin
wait(s)
end
```
We could also expose some hooks to do request/response with individual connections (#353 was an attempt at this). If we do request/response with scopes, the response would have to be a set of responses (corresponding to responses for all of the active connections for a scope).
This might not be …

Re-work messaging interface.

---

test/blink-tests.jl

Issue #375: This change resolves a warning that was being thrown during test execution

Update blink-test.jl to use preferred macro

---

src/providers/mux.jl

The docstring says:
```julia
webio_serve(app, port=8000)
Serve a Mux app which might return a WebIO node.
```
but, frustratingly, it does not currently accept a `Mux.app`. This PR trivially fixes this issue.

webio_serve(::Mux.App)

---

src/WebIO.jl

If you statically compile an application that uses WebIO, it will attempt to run this Module __init__ at runtime, but of course those source files will no longer be present once the application has been downloaded to a user's computer.
Please see these sections from the PackageCompilerX for an overview of relocatability:
- https://kristofferc.github.io/PackageCompilerX.jl/dev/apps/#Relocatability-1
- https://kristofferc.github.io/PackageCompilerX.jl/dev/devdocs/relocatable_part_3/
(I made this code change months ago but never sent it for review, so i don't remember what the errors were. But rereading the diff, it seems reasonable. I'll rebase and update it now..)

Make WebIO statically compilable (relocatable): don't run `include()`s in __init__

---

src/connection.jl

As discussed with @travigd this message keeps popping up randomly and seems to make Juno overall more laggy (in particular in combination with `TableView`) so this is the nuclear option - NB I don't really know what the function does overall so this might well be a bad idea!

Remove `@info` output

---

src/connection.jl

Helps with JuliaGizmos/Interact.jl#290.
It doesn't solve that issue yet, since errors are still swallowed if produced in the initial position of the `@manipulate` slider.

Show exception with stack trace on send_message error

---

packages/mux-provider/src/mux.ts

fixes https://github.com/JuliaGizmos/WebIO.jl/issues/382
---
Manually tested with the following:
- in `~/.julia/dev/WebIO/` :
```
pkg> test WebIO
```
this builds the JS bundles under `deps/bundles/` (and also runs the tests locally)
- in some tmp folder
```
pkg> activate .
pkg> add Interact Mux
pkg> dev WebIO
pkg> st
[c601a237] Interact v0.10.3
[a975b10e] Mux v0.7.1
[0f1e0344] WebIO v0.8.13 [`~/.julia/dev/WebIO`]
julia> using WebIO, Interact, Mux
julia> function gui()
but = button("click me")
on(but) do _
println("was clicked")
end
but
end
gui (generic function with 1 method)
julia> Mux.@app app = (Mux.defaults,
page("/", req->gui()),
page("/hallo", req->gui()),
page("/hallo/hello", req->gui()),
Mux.notfound())
julia> webio_serve(app, 8000)
Task (runnable) @0x00007f359a5adae0
```
where …

Fix getMuxWSUrl for location.pathname other than "/"

---

src/scope.jl

Tiny changes to remove deprecation warning for Base.@get!().

Fixed @get! deprecation warning

---

src/WebIO.jl
src/providers/blink.jl
src/providers/generic_http.jl
src/providers/ijulia.jl
src/providers/mux.jl

This fixes the issue reported in https://github.com/JuliaLang/PackageCompiler.jl/issues/650

do not try to load external packages in Requires.jl required files

---

.github/workflows/CompatHelper.yml

This is aimed at running the tests (in the new and improved "fail if the upgraded version wasn't used" manner). This package is holding back Observables, would be nice to fix.

Update CompatHelper to v3

---

packages/blink-provider/package.json
packages/generic-http-provider/package.json
packages/mux-provider/package.json
packages/package.json
packages/webio/package.json
packages/webpack.config.js

Updates webpack to fix work on new nodejs.

Fix frontend test

---

.github/workflows/tests.yml
Project.toml

Since #497, we only support Observables.jl 0.5 and up, which only supports Julia 1.6 and up. I updated the GitHub Actions to only run tests on Julia 1.6 and up, and updated the Project.toml to drop versions that we can't test.

Set minimum Julia version to 1.6

---

Project.toml

WebSockets support 1.6.0
As interface to websockets didn't change, there is no code change. 
I also run this version of WebIO against not yet released Blink (https://github.com/JuliaGizmos/Blink.jl/pull/295) and Blink tests pass. 
yes, in the PR the Blink is not actually using WebSockets, but unless WebIO moves to latest WebSockets, Blink cannot upgrade to latest HTTP

WebSockets 1.6.0
